package DTI;

public enum MessageType {
    MY_COINS,
    MINT,
    SPEND,
    MY_NFT,
    MINT_NFT,
    REQUEST_NFT_TRANSFER,
    CANCEL_REQUEST_NFT_TRANSFER,
    MY_NFT_REQUEST,
    PROCESS_NFT_TRASNFER
}
